name: CI

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/ci.yml'
      - 'packages/**'
      - '!packages/**/README.md'
      - 'scripts'
      - 'utils/**'
      - '.eslintignore'
      - '.eslintrc'
      - '.prettierrc'
      - 'babel.config.json'
      - 'jest.config.js'
      - 'package.json'
      - 'package-lock.json'
      - 'sonar-project.properties'
      - 'tsconfig.json'
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/ci.yml'
      - 'packages/**'
      - '!packages/**/README.md'
      - 'scripts'
      - 'utils/**'
      - '.eslintignore'
      - '.eslintrc'
      - '.prettierrc'
      - 'babel.config.json'
      - 'jest.config.js'
      - 'package.json'
      - 'package-lock.json'
      - 'sonar-project.properties'
      - 'tsconfig.json'
jobs:
  testing:
    name: Testing and Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      SONAR_VERSION: 4.2.0.1873

    steps:
      - name: Checkout project code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.11
      - name: Installation
        run: |
          npm ci
          npm run bootstrap
      - name: Building
        run: npm run build
      - name: Check
        run: npm run lint & npm run typecheck
      - name: Testing
        run: npm run test:coverage
        env:
          CI: true
      - name: Analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
