name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  testing:
    name: Testing and SonarCloud Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout project code
        uses: actions/checkout@v2
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Installation
        run: |
          npm ci
          npx lerna bootstrap
      - name: Testing
        run: npm run test:coverage
        env:
          CI: true
