name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  testing:
    name: Testing and Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout project code
        uses: actions/checkout@v2
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Installation
        run: |
          npm ci
          npx lerna bootstrap
      - name: Building
        run: npx lerna run build
      - name: Testing
        run: npm run test:coverage
        env:
          CI: true
      - name: Download Sonar Scanner
        if: steps.sonar-cache.outputs.cache-hit != 'true'
        run: sh scripts/sonar-scanner-load.sh
        env:
          SONAR_SCANNER_VERSION: 4.2.0.1873
      - name: Run Sonar Scanner
        run: sh scripts/sonar-scanner-run.sh
        env:
          SONAR_SCANNER_VERSION: 4.2.0.1873
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
